services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INIT DB_DATABASE: FamilyCashCard

  app:
    build: .
    container_name: family-cash-card-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/FamilyCashCard

volumes:
  mongo_data:
